services:
  website:
    image: nginx:latest
    ports:
      - "8080:80"
  database:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_USER: "Rahi" 
           
